In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn import linear_model
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [33]:
df = pd.read_csv('paddyph1.csv')
df

,Taluks,Soil,Paddy variety,Rainfall,Temperature,Nitrogen,Soil ph,Duration,Season,Yield
0,T.Kallupatti,Clay Soil,PMK (R) 3,1129.0,34.4,200.00,8.40,115,Semi-dry,3500
1,Vadipatti,Red soil,ADT 36,1076.8,33.2,220.00,9.00,110,"Navarai,Kar",4000
2,Madurai South,Red soil,ADT(R) 44,815.9,32.3,322.00,6.23,148,Samba,6214
3,Kallikudi,Black soil,IR 50,1062.0,33.0,221.52,8.14,110,Kar,4200
4,Tirumangalam,Black soil,white Ponni,997.6,30.0,230.52,7.89,140,"Samba,Thaladi",4500
...,...,...,...,...,...,...,...,...,...,...
165,Madurai South,Red soil,ADT 43,815.9,30.6,325.45,7.48,110,Kar,5900
166,Vadipatti,Red soil,IR 20,1076.8,33.2,233.45,7.94,135,"Samba,Thaladi",5000
167,Madurai West,clay loam,ADT 40,915.1,31.4,271.56,6.09,150,Samba,5500
168,Madurai East,Red loam,ASD 19,837.2,29.8,317.45,7.80,127,"Samba,Thaladi",5800
169,Tirumangalam,Red soil,MDU 3,997.6,33.5,229.48,6.48,125,Thaladi,5000

In [35]:
model = preprocessing.LabelEncoder()

In [40]:
df['Taluks']=model.fit_transform(df['Taluks'])
df['Soil']=model.fit_transform(df['Soil'])
df['Paddy variety']=model.fit_transform(df['Paddy variety'])
df['Season']=model.fit_transform(df['Season'])
df

,Taluks,Soil,Paddy variety,Rainfall,Temperature,Nitrogen,Soil ph,Duration,Season,Yield
0,6,1,26,1129.0,34.4,200.00,8.40,115,6,3500
1,10,4,2,1076.8,33.2,220.00,9.00,110,3,4000
2,3,4,9,815.9,32.3,322.00,6.23,148,4,6214
3,0,0,21,1062.0,33.0,221.52,8.14,110,0,4200
4,8,0,32,997.6,30.0,230.52,7.89,140,5,4500
...,...,...,...,...,...,...,...,...,...,...
165,3,3,8,815.9,30.6,325.45,7.48,110,0,5900
166,10,4,19,1076.8,33.2,233.45,7.94,135,5,5000
167,4,5,6,915.1,31.4,271.56,6.09,150,4,5500
168,1,2,13,837.2,29.8,317.45,7.80,127,5,5800
169,8,3,23,997.6,33.5,229.48,6.48,125,7,5000

In [41]:
x = df.drop(['Yield'],axis= 1)
y = df['Yield']

In [43]:
xtrain,xtest,ytrain,ytest = sklearn.model_selection.train_test_split(x,y,train_size = 0.7)
print(xtrain.shape)
print(ytrain.shape)

(118, 9)
(118,)

In [44]:
mlr = LinearRegression()
mlr.fit(xtrain,ytrain)

LinearRegression()

In [46]:
print(f'Correlation Coefficient - {mlr.coef_}')
print(f'Intercept - {mlr.intercept_}')

Correlation Coefficient - [  20.38183533   42.08978811    1.32747505    1.59563784  -57.17501337
   16.32104717 -255.18609573    6.42438545  -11.11672315]
Intercept - 2002.8644112165944

In [48]:
mlr_pred = mlr.predict(xtest)
a = mlr.score(xtest,ytest)

0.9142973815667788

In [53]:
ls = Lasso()
ls.fit(xtrain,ytrain)

Lasso()

In [54]:
ls_pred = ls.predict(xtest)
b = ls.score(xtest,ytest)

0.9143642811351853

In [56]:
rg = Ridge()
rg.fit(xtrain,ytrain)

Ridge()

In [57]:
rg_pred = rg.predict(xtest)
c = rg.score(xtest,ytest)
#Taluks	Soil	Paddy variety	Rainfall		Temperature Nitrogen	Soil ph	Duration	Season	Yield

0.9142582500644528

In [60]:
pip install mixtend
#6	1	26	1129.0	34.4	200.00	8.40	115	6	3500

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement mixtend (from versions: none)
ERROR: No matching distribution found for mixtend

In [ ]:
6	1	26	1129.0	34.4	200.00	8.40	115	6	3500
1	10	4	2	1076.8	33.2	220.00	9.00	110	3	4000
2	3	4	9	815.9	32.3	322.00	6.23	148	4	6214
3	0	0	21	1062.0	33.0	221.52	8.14	110	0	4200
4	8	0	32	997.6	30.0	230.52	7.89	140	5	4500
...	...	...	...	...	...	...	...	...	...	...
165	3	3	8	815.9	30.6	325.45	7.48	110	0	5900
166	10	4	19	1076.8	33.2	233.45	7.94	135	5	5000
167	4	5	6	915.1	31.4	271.56	6.09	150	4	5500
168	1	2	13	837.2	29.8	317.45	7.80	127	5	5800
169	8	3	23	997.6	33.5	229.48	6.48	125	7	5000

In [78]:
i = 1
for i in range(5):
  Taluks = int(input("Enter Taluks:"))
  Soil = int(input("Enter Soil:"))
  Paddy_variety = int(input("Enter Paddy variety:"))
  Rainfall = float(input("Enter Rainfall:"))
  Temperature = float(input("Enter Temperature:"))
  Nitrogen = float(input("Enter Nitrogen: "))
  Soil_ph = float(input("Enter Soil ph: "))
  Duration = int(input("Enter Duration: "))
  Season = int(input("Enter Season: "))
  mlrm = mlr.predict([[Taluks,Soil,Paddy_variety,Rainfall,Temperature,Nitrogen,Soil_ph,Duration,Season]])
  lsm = ls.predict([[Taluks,Soil,Paddy_variety,Rainfall,Temperature,Nitrogen,Soil_ph,Duration,Season]])
  rgm = rg.predict([[Taluks,Soil,Paddy_variety,Rainfall,Temperature,Nitrogen,Soil_ph,Duration,Season]])
  print(f'MLR {float(mlrm)},Lasso - {float(lsm)}, Ridge - {float(rgm)}')

Enter Taluks:6
Enter Soil:1
Enter Paddy variety:26
Enter Rainfall:1129
Enter Temperature:34.4
Enter Nitrogen: 200
Enter Soil ph: 8.40
Enter Duration: 115
Enter Season: 6

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

MLR 3829.164438253,Lasso - 3831.190659936883, Ridge - 3829.3948717543567
Enter Taluks:10
Enter Soil:4
Enter Paddy variety:2
Enter Rainfall:1076.8
Enter Temperature:33.2
Enter Nitrogen: 220
Enter Soil ph: 9
Enter Duration: 110
Enter Season: 3

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

MLR 4164.956991802224,Lasso - 4166.579653628543, Ridge - 4171.398708647968
Enter Taluks:3
Enter Soil:4
Enter Paddy variety:9
Enter Rainfall:815.9
Enter Temperature:32.3
Enter Nitrogen: 322
Enter Soil ph: 6.23
Enter Duration: 148
Enter Season: 4

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

MLR 6271.354290678633,Lasso - 6271.315504012202, Ridge - 6271.666104443271
Enter Taluks:0
Enter Soil:0
Enter Paddy variety:21
Enter Rainfall:1062
Enter Temperature:33
Enter Nitrogen: 221.52
Enter Soil ph: 8.1
Enter Duration: 110
Enter Season: 0

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

MLR 4093.6467221010375,Lasso - 4096.305642156216, Ridge - 4094.083344500803
Enter Taluks:8
Enter Soil:0
Enter Paddy variety:32
Enter Rainfall:997.6
Enter Temperature:30
Enter Nitrogen: 230.52
Enter Soil ph: 7.89
Enter Duration: 140
Enter Season: 5
MLR 4677.696045947016,Lasso - 4678.233920696262, Ridge - 4681.066518686484

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

In [ ]:
1	26	1129.0	34.4	200.00	8.40	115	6	3500
10	4	2	1076.8	33.2	220.00	9.00	110	3	4000
3	4	9	815.9	32.3	322.00	6.23	148	4	6214
0	0	21	1062.0	33.0	221.52	8.14	110	0	4200
8	0	32	997.6	30.0	230.52	7.89	140	5	4500
3	3	8	815.9	30.6	325.45	7.48	110	0	5900
10	4	19	1076.8	33.2	233.45	7.94	135	5	5000
4	5	6	915.1	31.4	271.56	6.09	150	4	5500
1	2	13	837.2	29.8	317.45	7.80	127	5	5800
8	3	23	997.6	33.5	229.48	6.48	125	7	5000